### ISSUE TITLE
Show Research Starters in article results

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1504]
![screen shot 2017-07-20 at 3 47 20 pm](https://user-images.githubusercontent.com/6945691/28442180-dfc8564c-6d63-11e7-833e-d1d41f04d7a4.png)

If there is a research starter returned for a search, show it on the first page of the search results, before the numbered results begin. 

If there is more than one, show only the first one.

- box style
     `border: 1px solid #8c1515`
     `box-shadow: 0 4px 8px -2px rgba(0,0,0,0.2);`
- close "x" positioned in upper right corner
   - add screen-reader text to the button: `<span class="sr-only">hide research starter</span>`
- Research Starter label is in css:
    ```
    .research-starter:before {
    position: absolute;
    top: 10px;
    left: 10px;
    font-size: 16px;
    font-weight: 400;
    color: #8c1515;
    text-transform: uppercase;
    letter-spacing: 1px;
    content: "Research Starter";
    ```
- `h3` is composed of
   - `<span class="sr-only">Research Starter: </span>
   - `<a>` with article title
- snippet of text
   - **need to determine where this comes from** - it should be the first ~3 lines of meaningful content in the article - i.e. not including the date updated. 
- image 
   - first image in the article, or whatever EDS provides as thumbnail
   - max-height 100px; width: auto; float: right; 

When the Research Starter box is closed:
![screen shot 2017-07-20 at 3 55 03 pm](https://user-images.githubusercontent.com/6945691/28442204-0bbb72de-6d64-11e7-93ed-9e7c388da10b.png)

- hide all content
- rotate the "close" icon 45 degrees
- change its "sr-only" text to "show research starter"

**Comment by drh-stanford** [comment]
@jvine the `float: right` on the image brings it out of the `research-starter` class box, as below:

I'm using the following CSS:

```css
.research-starter:before {
  position: relative;
  top: 10px;
  left: 10px;
  font-size: 16px;
  font-weight: 400;
  color: #8c1515;
  text-transform: uppercase;
  letter-spacing: 1px;
  content: "Research Starter";
}

.research-starter {
  border: 1px solid #8c1515;
  box-shadow: 0 4px 8px -2px rgba(0,0,0,0.2);
  h3, p {
    margin: 10px 25px;
  }

  img {
    max-height: 100px;
    width: auto;
    float: right;
  }
}
```

![screen shot 2017-07-24 at 4 11 15 pm](https://user-images.githubusercontent.com/1861171/28548758-c205b9fe-708a-11e7-846d-677abda05008.png)
