### ISSUE TITLE
Update pageable locations for Library = HOPKINS

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3104]
The Marine Biology Librarian (Amanda Whitmire) has requested updates to the "pageable_locations" lists for HOPKINS. https://github.com/sul-dlss/SearchWorks/blob/1c4b71e34f2490b888b5babbd69b84415dbd6fe2/config/settings.yml#L181

We should **include** the following Locations:
GRAPHICNOV
CHILDRENYA

We should **remove** the following location:
THESIS

**Comment by cbeer** [comment]
We also need to make a corresponding change in sul-requests.

**Comment by thatbudakguy** [comment]
It doesn't seem like hopkins has a dedicated section in the sul-requests `pageable` config. Should I create one and set:
```yml
pageable:
- library: HOPKINS
   location:
    - CHILDRENYA
    - GRAPHICNOV
    - MEDIA
    - OVERSIZED
    - POPSCI
    - SERIALS
    - SHELBYSER
    - SHELBYTITL
    - STACKS
```
?
