### ISSUE TITLE
Refactor library-keyed constants

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#3148]
Searchworks has a plethora of constants for looking up data based on the library code. So there's less churn (and fewer places to check) in FOLIO-land, can we collect the constants into one data structure (perhaps in `Settings`?).

Constants of interest may include:
- `Constants::LIBRARY_ABOUT`
- `Constants:: STACKMAP_LIBS`
- `Constants::STACKMAP_SKIPLIST`
- `Constants::HOOVER_LIBS`
- `Constants::LIB_TRANSLATIONS`
- `Constants::HOURS_LOCATIONS`
- `Settings.STACKMAP_API_URL`
- `Settings.EZPROXY`

Might be easier to deal with in a structure like:

```
libraries:
  GREEN:
    name:
    about_url:
    hours_api_url:
    stackmap_api:
    ignored_stackmap_locations:
    thumbnail:
  HOOVER:
    suppress_items_list_on_results_view: true
    suppress_location_request_link: true
  DEFAULT:
    name: 
    ezproxy_host:
```

sul-requests has a similar structure, and it might be nice to align some of the keys: https://github.com/sul-dlss/sul-requests/blob/master/config/settings.yml#L112

(see https://github.com/sul-dlss/SearchWorks/issues/3136)
