### ISSUE TITLE
BS4 branch: "Check availability" button

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/SearchWorks#3564]
This seems broken. In production, there is only a `before` style applied:
```css
.glyphicon-chevron-right::before {
    content: "\e080";
}
```

In BS4 branch we have both `::before` and `::after` applied to nested elements:
<img width="917" alt="Screen Shot 2023-09-28 at 9 52 42 AM" src="https://github.com/sul-dlss/SearchWorks/assets/1328900/dfb305a6-801f-4c4d-a9b7-6ee59cd42f19">
```css
.bi-chevron-right::before {
    content: "\f285";
}
.accordion-sections .accordion-section .header::after {
    content: "❯";
    float: right;
}
```

production
<img width="340" alt="Screen Shot 2023-09-28 at 9 49 13 AM" src="https://github.com/sul-dlss/SearchWorks/assets/1328900/3cadadb1-57a6-44b2-acd2-8d6acd0d34cb">

BS4/staging
<img width="339" alt="Screen Shot 2023-09-28 at 9 49 08 AM" src="https://github.com/sul-dlss/SearchWorks/assets/1328900/6134f1b4-dabd-4fc1-8ed6-0d9021a6b6cb">
